### ISSUE TITLE
Wording on templates and Domain requirements page

### ISSUE THREAD

**Issue by trebok-CISA** [cisagov/dotgov-home#111]
I noticed the following on the dotgov.gov site and perhaps should be updated:
1. Remove "and pay the registration fee" -   https://home.dotgov.gov/registration/
2. Include the word "not"? (... but which are <not> publicly controlled by the state...)  - https://home.dotgov.gov/registration/requirements/#special-district-functions
3. Interstate Authorization Letter template - Name of link is not fully qualified like on the other templates (.../registration/requirements)
4. Tribal Authorization Letter template - "you tribe" in first paragraph

**Comment by h-m-f-t** [comment]
Thanks! I can confirm that I've already captured these in a to-be-published branch – except for 2, which does indeed appear to be a drafting error in the original coordination docs with OMB.

**Comment by h-m-f-t** [comment]
Fixed in #112.
