### ISSUE TITLE
Help Center FAQ question mis-categorized

### ISSUE THREAD

**Issue by trebok-CISA** [cisagov/dotgov-home#114]
In the [Help Center](https://home.dotgov.gov/help/), I believe that this question is in the wrong category. Instead of "DNS" it likely should be under "Domain Requirements"

"What are the valid characters for a domain name and how long can it be?"

**Comment by h-m-f-t** [comment]
Closing this old issue, as we'll replace this site [getgov-home](https://github.com/cisagov/getgov-home).
