### ISSUE TITLE
Unresolved domains used as examples in requirements.md 

### ISSUE THREAD

**Issue by colinmurphy01** [cisagov/dotgov-home#136]
The following links don't resolve or throw an error:
- All of the state origin [examples](https://github.com/cisagov/dotgov-home/blob/e9593184d369aada7350fb4d929886e7168bcd72/pages/registration/requirements.md?plain=1#L155-L158)
- [gulfcoastwaterauthority.gov](https://github.com/cisagov/dotgov-home/blob/e9593184d369aada7350fb4d929886e7168bcd72/pages/registration/requirements.md?plain=1#L189)
- [Coloradoarta.gov](https://github.com/cisagov/dotgov-home/blob/e9593184d369aada7350fb4d929886e7168bcd72/pages/registration/requirements.md?plain=1#L156)
- [PortHouston.gov](https://github.com/cisagov/dotgov-home/blob/e9593184d369aada7350fb4d929886e7168bcd72/pages/registration/requirements.md?plain=1#L209)

**Comment by h-m-f-t** [comment]
Hi @colinmurphy01. When you say "don't resolve", are you talking specifically about getting no response to web requests to the domain?

**Comment by colinmurphy01** [comment]
I think coloradoarta was the only url that returned a 404 error. The others else returned `DNS_PROBE_FINISHED_NXDOMAIN`

**Comment by h-m-f-t** [comment]
:wave:

We'll use different domains on our [forthcoming site](https://github.com/cisagov/getgov-home).
