### ISSUE TITLE
Clarify policy "No Political or Campaign Information"

### ISSUE THREAD

**Issue by pzb** [cisagov/dotgov-home#17]
> No Political or Campaign Information: The Gov Internet domain is for the operation of government, not the political, political party, or campaign environment. No campaigning can be done using .gov domains. The Gov Internet domain websites may not be directly linked to or refer to websites created or operated by a campaign or any campaign entity or committee. No political sites or party names or acronyms can be used. Separate websites and e-mail on other top-level domains (TLDs), such as .org, will have to be used for political activity.

The fourth and fifth sentences seem to exceed the intent of the policy.  The FEC and websites of Secretaries of State (or other election officials) frequently link to campaign entity websites as part of official voters guides and campaign finance disclosure statements.  Domains such as `democrats.gov` and `republicans.gov` clearly include political party names and `gopleader.gov`, `gop.gov`, `dems.gov` and others include acronyms or abbreviations for political parties.

What about just dropping these two sentences?  Also maybe consider adding .com as the two parties with the most seats in the House and Senate split between `.com` and `.org` for their primary websites.

**Comment by h-m-f-t** [comment]
I've added .com. As additional .gov policy changes are made, I think

**Comment by h-m-f-t** [comment]
The new .gov policy, released in April 2021, [says](https://home.dotgov.gov/registration/requirements/#prohibited-activities) simply:
>A .gov domain must not be used for political campaign purposes.
