### ISSUE TITLE
Consider serving the data files from the DotGov.gov domain

### ISSUE THREAD

**Issue by lachellel** [cisagov/dotgov-home#69]
@h-m-f-t 

The data files referenced [here](https://github.com/GSA/dotgov-home/blob/master/pages/data.md) are currently served from here:

- https://github.com/GSA/data/tree/master/dotgov-domains

A team would like to use these data files for this: https://github.com/uspki/policies

- Consuming the data files from the github.com reference directly may pose a problem (add significant time) for the team 
- What are the considerations (pros/cons) for not serving the data files from home.DotGov.gov?
- Would you consider incorporating changes to **also** serve the data files from home.DotGov.gov if we could identify simple dependencies or changes to processes, and submit some PRs for review? 

Thanks for all thoughts!

**Comment by h-m-f-t** [comment]
I'd like to better understand the request, too -- though I see value in domain data being clearly available at a dotgov.gov hostname. 

Given that this site is managed via [Federalist](https://federalist.18f.gov), and the change control sits atop GitHub, the thing that would be lost in a move would be a unified history of .gov domain changes from the last few years (unless there's a way of moving that history to a new repo that I'm not aware of).

While there may be many active users of .gov data, we'd definitely want to give notice of a change to the Pulse/Digital Dashboard projects and @dhs-ncats (cc: @jsf9k/@dav3r), given that I think they are pulling from the raw GitHub link.

**Comment by h-m-f-t** [comment]
I've taken a swing at this in the `domains-on-dotgov-gov` branch. You can see what this will look like [here](https://federalist-proxy.app.cloud.gov/preview/gsa/dotgov-home/domains-on-dotgov-gov/data/) (though with a `federalist-proxy.app.cloud.gov` URL).

Should we merge this, domain data would be available at `https://home.dotgov.gov/domains/current-full.csv`. 

Feedback welcome! 

cc: @dhs-ncats @jsf9k @dav3r

**Comment by konklone** [comment]
How about a data.dotgov.gov subdomain pointed at the GSA/data repo via Federalist? And then rename the repo dotgov-data. That would allow the website and data publication to be managed separately, and their repos/permissions optimized for both.

**Comment by h-m-f-t** [comment]
The files are still served from GitHub [`githubusercontent.com`] but are now managed at https://github.com/cisagov/dotgov-data. See https://github.com/GSA/data/issues/322.
