### ISSUE TITLE
Password change before 2FA?

### ISSUE THREAD

**Issue by davegriffin** [cisagov/dotgov-home#83]
I was just prompted to change my password (which I guess I'm forced to do once a year, that's cool)...  but the password change form came up BEFORE I entered the 2FA code!  This seems, well, backwards....

Suggest you complete the authentication process before changing passwords.

**Comment by h-m-f-t** [comment]
Thanks, @davegriffin. CISA began maintaining .gov earlier this year, and I'm unsure when it changed, but this has now been resolved. Forced password changes are also going away (unless there's evidence of breach).
