### ISSUE TITLE
".gov" is commercial or non-commercial?

### ISSUE THREAD

**Issue by sagarpatel279** [cisagov/dotgov-home#85]

**Comment by timrossback** [comment]
Non-commercial. Only a US Government organisation, which categorically is public, can register a .gov domain.

**Comment by h-m-f-t** [comment]
Yep. .gov domains must not be used for commercial purposes:  https://home.dotgov.gov/registration/requirements/#prohibited-activities

**Comment by 25ten** [comment]
.gov is a non commercial domain extinction it is owned by the united stares government [https://csrc.nist.gov/](url)
.com .net .org and many other are commercial  domain extinction
following is the .com example
[https://www.jokes4sms.com/2021/09/non-veg-jokes.html](url)
