### ISSUE TITLE
dotgov.gov is a terrible domain name

### ISSUE THREAD

**Issue by eberlyn** [cisagov/dotgov-home#88]
I think dotgov.gov (or home.dotgov.gov) is a terrible domain name. It is really difficult to say 'to find more information, go to home dot dotgov dot gov), and encourages the creation of bad domains. I think this domain should be renamed to something that is easier to say and does not include more than one dot in it (not including "www."), as I think domains with more than one dot are hard to remember.

**Comment by dcinzona** [comment]
How about domains.gov? or webdomains.gov? or dns.gov?

**Comment by todrobbins** [comment]
Or maybe `registrar.gov`?

**Comment by dcinzona** [comment]
@todrobbins I dig it.

**Comment by h-m-f-t** [comment]
`dotgov.gov` is really fun to say, but it is hard to communicate, especially when you add hostname info (try saying `home.dotgov.gov` out loud). 

The name probably won't stick around forever.
