### ISSUE TITLE
Don't glorify HTTPS

### ISSUE THREAD

**Issue by mikaturk** [cisagov/dotgov-home#89]
"The https:// ensures that you are connecting to the official website"
is one of the sentences in the section on how to know a site is an official one, teaching people that https means a safe site is a bad practice (google and mozilla realized this a long while ago, no more green icons) getting an TLS cert for a domain that looks similar to a real one is too easy and might trick consumers into trusting something they shouldn't.

**Comment by ryanwoldatwork** [comment]
For reference, the latest USWDS still contains `https` in the copy.

https://designsystem.digital.gov/components/banner/

**Comment by h-m-f-t** [comment]
It's definitely true that there's nothing inherent to HTTPS that makes a particular site trustworthy. However, when a website that uses HTTPS also uses a .gov domain, the public can have reasonably strong expectations that the site is _actually affiliated_ with a US-based government org and that the content received is what that org intended to publish.

@ryanwoldatwork is right that the USWDS banner still include HTTPS copy; see [that PR](https://github.com/uswds/uswds/pull/3524) for some more background.
